library(readr)
library(tseries)
library(fUnitRoots)
library(lmtest)
library(forecast)
library(h2o)
library(caret)
library(randomForest)
library(tsibble)
library(lubridate)
library(dplyr)

thesis <- paste0(getwd(),"/")
