library(readr)
library(tseries)
library(fUnitRoots)
library(lmtest)
library(forecast)
library(h2o)
library(caret)
library(randomForest)
library(tsibble)
library(tidyr)
library(lubridate)
library(dplyr)
library(tictoc)

thesis <- paste0(getwd(),"/")
import <- paste0(thesis,"data/import/")
export <- paste0(thesis, "data/export/")
