library(readr)
library(tseries)
library(fUnitRoots)
library(lmtest)
library(forecast)
library(caret)
library(randomForest)
library(tsibble)
library(tidyr)
library(lubridate)
library(tictoc)
library(vars)
library(dplyr)
library(parallel)
library(iterators)
library(foreach)
library(doParallel)


thesis <- paste0(getwd(),"/")
import <- paste0(thesis,"data/import/")
export <- paste0(thesis, "data/export/")
