library(readr)
library(tseries)
library(fUnitRoots)
library(lmtest)
library(forecast)
library(caret)
library(randomForest)
library(tsibble)
library(tidyr)
library(lubridate)
library(tictoc)
library(vars)
library(dplyr)
library(parallel)
library(iterators)
library(foreach)
library(doParallel)

make_forest <- paste0(getwd(),"/")
thesis <- substr(make_forest, 1, (nchar(make_forest) - 12))
import <- paste0(thesis,"data/import/")
export <- paste0(thesis, "data/export/")
